version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt
    ports: ["80:80","443:443"]
    depends_on: [api]
  api:
    build: ./api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - REDIS_URL=${REDIS_URL}
    depends_on: [redis]
  discord:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_URL=http://api:5000
    depends_on: [api]
  redis:
    image: redis:6-alpine
volumes:
  certs:
