version: '3.8'

services:
  api:
    image: anhsp/ai-program-api:latest
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    restart: always

  bot:
    image: anhsp/ai-program-bot:latest
    env_file:
      - ../.env
    restart: always

  redis:
    image: redis:6-alpine
    restart: always

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - bot
    restart: always

volumes:
  certs:

