name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & test tools
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API image
        run: |
          docker build -t anhsp/ai-program-api:latest api/

      - name: Push API image
        run: |
          docker push anhsp/ai-program-api:latest

      - name: Build Discord Bot image
        run: |
          docker build -t anhsp/ai-program-bot:latest discord-bot/

      - name: Push Bot image
        run: |
          docker push anhsp/ai-program-bot:latest
deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/ai-program
            git pull origin main            # ← tự động kéo code mới
            cd infra
            docker-compose pull            # kéo image mới từ Docker Hub
            docker-compose up -d --remove-orphans
          EOF

